name: Continuous Deployment
on:
  pull_request:
    types: [closed]
    branches:
      - main
permissions:
  contents: read
jobs:
  build-linux-wheels:
    name: Build Linux wheels
    runs-on: ubuntu-latest
    strategy:
      matrix:
        py-arg: ['3.8.16 3.8', '3.9.19 3.9', '3.10.14 3.10', '3.11.0 3.11', '3.12.0 3.12', '3.13.0 3.13', '3.14.0 3.14']
    steps:
      - uses: actions/checkout@v5
      - name: Build 
        run: |
          docker run --rm -v $(pwd):/io quay.io/pypa/manylinux2014_x86_64:${{ matrix.py-arg == '3.8.16 3.8' && '2025.02.23-1' || 'latest' }} bash \
            /io/build-wheels.sh ${{ matrix.py-arg }}
      - name: Cache
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.py-arg }} wheel
          path: dist/wheelhouse/*-manylinux*.whl
  build-macos-arm64-wheel:
    name: Build arm64 wheels on macos-26
    runs-on: macos-26
    strategy:
      matrix:
        py-arg: ['cp38', 'cp39', 'cp310', 'cp311', 'cp312', 'cp313', 'cp314']
        os-arg: ['arm64']
    steps:
      - uses: actions/checkout@v5
      - name: Install Rust Dependency
        run: |
         rustup update stable
         rustup default stable
         rustup target add aarch64-apple-darwin
      - name: Build
        uses: pypa/cibuildwheel@v3.2.0
        env:
          CIBW_ARCHS_MACOS: ${{ matrix.os-arg }} 
          CIBW_BUILD: ${{ matrix.py-arg }}-macosx_${{ matrix.os-arg }}
      - name: Cache
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.py-arg }}-macosx_${{ matrix.os-arg }}
          path: wheelhouse/*.whl
  build-macos-x86-wheel:
    name: Build x86 wheels on macos-26-intel
    runs-on: macos-26-intel
    strategy:
      matrix:
        py-arg: ['cp38', 'cp39', 'cp310', 'cp311', 'cp312', 'cp313', 'cp314']
        os-arg: ['x86_64']
    steps:
      - uses: actions/checkout@v5
      - name: Update Rust toolchain
        run: |
          rustup update stable
          rustup default stable
      - name: Build
        uses: pypa/cibuildwheel@v3.2.0
        env:
          CIBW_ARCHS_MACOS: ${{ matrix.os-arg }} 
          MACOSX_DEPLOYMENT_TARGET: '10.12'
          CIBW_BUILD: ${{ matrix.py-arg }}-macosx_${{ matrix.os-arg }}
      - name: Cache
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.py-arg }}-macosx_${{ matrix.os-arg }}
          path: wheelhouse/*.whl
  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    needs: [build-linux-wheels, build-macos-arm64-wheel, build-macos-x86-wheel]
    steps:
      - name: start deploying
        uses: actions/checkout@v5
      - name: Download wheels
        uses: actions/download-artifact@v8
        with:
         path: wheelhouse
         merge-multiple: true
      - name: move wheel
        run: | 
         mkdir dist
         mv wheelhouse/*.whl dist/
         ls
         ls dist
      - name: Upload Wheels
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME}}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD}}
        run: |
          pip install twine
          pip install pexpect
          python -m twine upload dist/*.whl